# Generated by Django 2.0 on 2017-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please fill your first name', max_length=100)),
                ('last_name', models.CharField(help_text='Please fill your last name', max_length=100)),
                ('email', models.EmailField(help_text='Please fill your email address', max_length=100)),
            ],
        ),
    ]
